# This is Sour's default configuration.
client:
  assets:
    - "mobile:#origin/assets/mobile/.index.source"
    - "mobile:https://static.sourga.me/blobs/6481-mobile/spicy-mobile.index.source"
    - "#origin/assets/desktop/.index.source"
    - "https://static.sourga.me/blobs/6481/.index.source"

cluster:
  logSessions: true

  assets:
    - "!http://localhost:1234/assets/desktop/.index.source"
    - "skip:https://static.sourga.me/blobs/6481/.index.source"

  presets:
    - name: "ffa-duel" 
      virtual: true
      config:
        defaultMode: "ffa"
        defaultMap: "turbine"
    - name: "insta-duel" 
      virtual: true
      config:
        defaultMode: "insta"
        defaultMap: "turbine"
    - name: "default" 
      default: true
      config:
        defaultMode: "coop"
        defaultMap: "xmwhub"
    - name: "ffa" 
      config:
        defaultMode: "ffa"
        defaultMap: "complex"
    - name: "insta" 
      config:
        defaultMode: "insta"
        defaultMap: "complex"
    - name: "explore" 
      config:
        matchLength: 180

  ingress:
    desktop:
      - port: 28785
        target: lobby
        serverInfo:
          enabled: true
          cluster: true
    web:
      port: 29999

  matchmaking:
    duel:
      - name: "ffa"
        preset: "ffa-duel"
        forceRespawn: "dead"
        default: true
      - name: "insta"
        preset: "insta-duel"
        forceRespawn: "dead"

  spaces:
    - preset: default
      config:
        alias: lobby
        links:
          - id: 77
            destination: home
          - id: 66
            destination: insta
          - id: 55
            destination: ffa
          - id: 11
            destination: home
          - id: 22
            destination: home
          - id: 33
            destination: home
          - id: 44
            destination: home
    - preset: explore
      exploreMode: true
      config:
        alias: explore
