# This is Sour's default configuration.
# It is validated against config/schema.cue.

client:
  enabled: true

  # All client URLs can use these template variables:
  # #host: replaced with window.location.host
  # #origin: replaced with window.location.origin (basically #protocol + #host)
  # #protocol: replaced with window.location.protocol e.g. https:

  # These are the URLs for each of the asset sources.
  # Order matters; the client uses the first map it finds.
  assets:
    # The client's asset sources may not be the same as the cluster's because
    # we might not know the hostname the user will be accessing Sour at ahead
    # of time. We can take advantage of the browser's automatic addition of the
    # hostname to bare absolute paths.
    - "#origin/assets/.index.json"

  # The URLs for all of the game servers, for now we only support one.
  clusters:
    # ws: and wss: are inferred
    - "#host/service/cluster/"

  # ws: and wss: are inferred
  proxy: "#host/service/proxy/"

proxy:
  enabled: true

# Sour clusters host game servers.
cluster:
  enabled: true
  assets:
    # This is not the same thing as client.assets because the cluster has to
    # specify complete URLs (and can access services using their addresses
    # inside the container.)
    - "http://localhost:1234/assets/.index.json"

  # We set the Sauerbraten `serverdesc` according to this template.
  # #id is replaced with the server's identifier.
  serverDescription: "Sour [#id]"

  # Server presets are templates for starting new servers, typically by a user through #creategame.
  # A mapping from preset name -> preset settings.
  presets:
    - name: "default" 
      # This means that if the user does not specify a config, we use this preset.
      default: true
      # If a config refers to a file that exists, we will just use that to start the server
      #config: /sour/config/server-init.cfg
      # You can also specify a CubeScript configuration for the server inline.
      config: |
        qserv_version "17"
        servermotd "Press Esc twice to change your name or adjust game options."
        maxclients 32
        defaultgamespeed 100
        defaultmodename "ffa"
        defaultmap "complex"
        autosendmap 1
        enable_passflag 1
        instacoop 0
        serverflagruns 1
        addbanner "^f7Sour ^f7is available online ^f1www.github.com/cfoust/sour^f7."
        addbanner "^f1[Tip]: ^f7Use ^f2#mapsucks ^f7to vote for an intermission."
        serverbotbalance 1
        lockmaprotation 0
        ffamaps = [
          complex dust2 turbine
        ]
        maprotationreset
        maprotation "*" $ffamaps

        maxteamkills 7
        teamkillkickreset
        teamkillkick "?capture" 10 30
        maxdemos 10
        updatemaster 0
        enablemultiplemasters 0
        serverconnectmsg 1
        welcomewithname 1
        no_single_private 0
        pingwarncustommsg "A little lagspike was detected, we just wanted to let you know."
        restrictpausegame 1
        restrictgamespeed 1
        restrictdemos 0
    - name: "1v1" 
      config: |
        qserv_version "17"
        servermotd "Press Esc twice to change your name or adjust game options."
        maxclients 32
        defaultgamespeed 100
        defaultmodename "ffa"
        defaultmap "complex"
        autosendmap 1
        enable_passflag 1
        instacoop 0
        serverflagruns 1
        addbanner "^f7Sour ^f7is available online ^f1www.github.com/cfoust/sour^f7."
        addbanner "^f1[Tip]: ^f7Use ^f2#mapsucks ^f7to vote for an intermission."
        serverbotbalance 1
        lockmaprotation 0
        ffamaps = [
          complex dust2 turbine
        ]
        maprotationreset
        maprotation "*" $ffamaps

        maxteamkills 7
        teamkillkickreset
        teamkillkick "?capture" 10 30
        maxdemos 10
        updatemaster 0
        enablemultiplemasters 0
        serverconnectmsg 1
        welcomewithname 1
        no_single_private 0
        pingwarncustommsg "A little lagspike was detected, we just wanted to let you know."
        restrictpausegame 1
        restrictgamespeed 1
        restrictdemos 0

  ingress:
    # Describes all of the ways desktop clients can join this cluster
    desktop:
      # The UDP port to listen on
      - port: 28785
        # The cluster command to run when an ENet client joins
        # This command must result in the client joining a server.
        command: join lobby
    # And web clients
    web:
      port: 29999

  # These are all of the game servers that will be started when the cluster starts.
  servers:
    # An alias replaces the ID of a server. For example, users could run
    # #join lobby (on desktop) or /join lobby (on the web)
    - alias: lobby
      preset: default
