version: '3'

services:
  sour-site:
    image: registry.digitalocean.com/cfoust/sour:latest
    container_name: sour-site
    environment:
      VIRTUAL_HOST: sourga.me
      VIRTUAL_HOST_ALIAS: www.sourga.me
      VIRTUAL_PORT: 1234
      LETSENCRYPT_HOST: sourga.me
      LETSENCRYPT_EMAIL: XXXXXXX
      ASSET_SOURCE: https://d2pz4qr8rxo7le.cloudfront.net/2bfc017.index.json
      GAME_SERVER: wss://server.sourga.me
    stdin_open: True
    tty: True
    networks:
      - letsencrypt

networks:
  letsencrypt:
    external: true

# vim: expandtab tabstop=2 softtabstop=2 shiftwidth=2
